### ISSUE TITLE
Installing on Mac

### ISSUE THREAD

**Issue by Nickspizza001** [BGI-SynBio/PyMOL-PUB#2]
`Adding PyMOL-PUB 1.1 to easy-install.pth file

Processing dependencies for PyMOL-PUB==1.1
Searching for pymol
Reading https://pypi.org/simple/pymol/
No local packages or working download links found for pymol
error: Could not find suitable distribution for Requirement.parse('pymol')`

I tried installing the package after installing PyMOL v 2.5.0

**Comment by ytchen-1** [comment]
The reason for this problem is that the PyMOL team does not distribute the PyMOL installation package on the pypi platform. Therefore, when the Mac automatically searches for the pymol on pypi, this issue arises.
If you have already installed PyMOL on your Mac, just make sure that the installed PyMOL and PyMOL-PUB can be used normally in the same Python environment, and this prompt can be ignored.
For instructions on how to install PyMOL on the Mac, please refer to this link (https://pymolwiki.org/index.php/MAC_Install).

**Comment by Nickspizza001** [comment]
Thank you very much @ytchen-1. I could not fix it on the Mac but I installed it easily on my Windows machine.
